// Generated by https://quicktype.io

export interface GetIDFilm {
    titulo:          string;
    episodio:        number;
    texto_apertura:  string;
    director:        string;
    productor:       string;
    fecha_estreno:   string;
    personajes:      string[];
    planetas:        string[];
    naves_estelares: string[];
    vehiculos:       string[];
    especies:        string[];
    url:             string;
    creado:          string;
    editado:         string;
}
