// Generated by https://quicktype.io

export interface GetIDPlanet {
    nombre:           string;
    diametro:         string;
    periodo_rotacion: string;
    periodo_orbital:  string;
    gravedad:         string;
    poblacion:        string;
    clima:            string;
    terreno:          string;
    superficie_agua:  string;
    residentes:       string[];
    peliculas:        string[];
    url:              string;
    creado:           string;
    editado:          string;
}
