// Generated by https://quicktype.io

export interface GetIDPeople {
    nombre:          string;
    anio_nacimiento: string;
    color_ojos:      string;
    genero:          string;
    color_cabello:   string;
    altura:          string;
    peso:            string;
    color_piel:      string;
    mundo_natal:     string;
    peliculas:       string[];
    especies:        string[];
    naves:           any[];
    vehiculos:       any[];
    url:             string;
    creado:          string;
    editado:         string;
}
