// Generated by https://quicktype.io

export interface GetIDSpecies {
    nombre:                  string;
    clasificacion:           string;
    designacion:             string;
    altura_promedio:         string;
    esperanza_vida_promedio: string;
    colores_ojos:            string;
    colores_cabello:         string;
    colores_piel:            string;
    lenguaje:                string;
    planeta_origen:          string;
    personas:                string[];
    peliculas:               string[];
    url:                     string;
    creado:                  string;
    editado:                 string;
}
