// Generated by https://quicktype.io

export interface GetIDStarships {
    nombre:                     string;
    modelo:                     string;
    clase_nave:                 string;
    fabricante:                 string;
    costo_creditos:             string;
    longitud:                   string;
    tripulacion:                string;
    pasajeros:                  string;
    velocidad_maxima_atmosfera: string;
    hiperimpulsor_clase:        string;
    MGLT:                       string;
    capacidad_carga:            string;
    consumibles:                string;
    peliculas:                  string[];
    pilotos:                    any[];
    url:                        string;
    creado:                     string;
    editado:                    string;
}
