export * from './nuevoFilm.response'
export * from './getIdFilm.response'
export * from './getIdPeople.response'
export * from './getIdPlanet.response'
export * from './getIdSpecies.response'
export * from './getIdStarships.response'
export * from './getIdVehiculos.response'